# Generated by Django 6.0.2 on 2026-02-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.CharField(max_length=200, unique=True)),
                ('short_url', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
